### ISSUE TITLE
icon\r file is treated as a document/file on Mac

### ISSUE THREAD

**Issue by domrout** [GateNLP/gate-top#2]
This file is created automatically on Mac for folders that have a custom icon in finder, without the user knowing about it. For datastore creation, this triggers a folder not empty error. For corpus creation this triggers a file with no data in it. Suggest finding a way to ignore it.

**Comment by greenwoodma** [comment]
Yes this cropped up on Monday as well. When did this start happening as this hasn't always been the case otherwise we'd have run into it every year as there is always someone with a Mac on the course and plenty in the group as well. Also do we know exactly what the filename is? it appeared to be Icon? when you looked from a command line

**Comment by greenwoodma** [comment]
This issue was moved to GateNLP/gate-core#12
